import streamlit as st
from ai_sql_generator import generate_sql_generic

st.set_page_config(page_title="AI SQL GENERATOR", page_icon="🛠️")

st.markdown("""
<style>
.stApp{
    background: linear-gradient(to bottom right, #f0f4f8, #d9e2ec);
}

div[data-testid="stTextInput"] input {
    border: 2px solid #4F8BF9;
    border-radius: 8px;
    padding: 10px;
}

div.stButton > button {
    background-color: #4F8BF9;
    color: white;
    border-radius: 8px;
    border: none;
    padding: 8px 24px;
    font-weight: 600;
}

div.stButton > button:hover {
    background-color: #3a6fd8;
    color: white;
}

div[data-testid="stCodeBlock"] {
    border: 1px solid #4F8BF9;
    border-radius: 8px;
}
</style>
""", unsafe_allow_html=True)

st.title("AI SQl Query Generator")
st.write("Describe any SQL scenario in plain English — no database connection needed. "
    "This just writes the query for you to use anywhere.")

scenario = st.text_area(
    "Describe your scenario:",
    placeholder="e.g. Write a query to find the highest salary in the employees table"
)

if st.button("Generate SQL"):
    if scenario.strip() == "":
        st.warning("Please describe a scenario first.")
    else:
        with st.spinner("Generating SQL..."):
            sql = generate_sql_generic(scenario)

        st.subheader("Generated SQL")
        with st.container(border=True):
            st.code(sql, language="sql")

        st.caption(
            "⚠️ This query was generated by AI and not executed against any real "
            "database. Review it before running it against your own data."
        )